import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import OpenCC from "opencc-js";
import { zhCN } from "../src/locales/zh-CN.ts";

const convert = OpenCC.Converter({ from: "cn", to: "twp" });

function mapStrings(value) {
	if (typeof value === "string") return convert(value);
	if (Array.isArray(value)) return value.map(mapStrings);
	if (value && typeof value === "object") {
		return Object.fromEntries(
			Object.entries(value).map(([key, child]) => [key, mapStrings(child)]),
		);
	}
	return value;
}

const output = `// Generated by scripts/generate-zh-tw.mjs. Do not edit.\nexport const zhTW = ${JSON.stringify(mapStrings(zhCN), null, "\t")} as const;\n`;
const target = fileURLToPath(new URL("../src/locales/zh-TW.generated.ts", import.meta.url));
await writeFile(target, output, "utf8");
