import { createServer } from "node:http";
import { appendBoundedTrace } from "./bounded-trace.ts";

// Authored deterministic model responses, not a simulated executor: the real
// built-in Pi ACP worker must execute every filesystem tool and produce its own
// native results before this provider reports a successful artifact check.
const artifactContent = "Artifact generated by the E2E built-in Pi Worker.\n";
const createWorkbook = `python3 - <<'PY'
import os
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
path = Path(os.environ["BEAR_OUTPUT_DIR"]) / "e2e-grid.xlsx"
ns = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
rows = "".join('<row r="%d">%s</row>' % (r, "".join('<c r="%s%d"><v>%d</v></c>' % (chr(64+c), r, (r-1)*5+c) for c in range(1, 6))) for r in range(1, 6))
with ZipFile(path, "w", ZIP_DEFLATED) as book:
    book.writestr("[Content_Types].xml", '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>')
    book.writestr("_rels/.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>')
    book.writestr("xl/workbook.xml", '<?xml version="1.0"?><workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Grid" sheetId="1" r:id="rId1"/></sheets></workbook>')
    book.writestr("xl/_rels/workbook.xml.rels", '<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>')
    book.writestr("xl/worksheets/sheet1.xml", '<?xml version="1.0"?><worksheet xmlns="'+ns+'"><dimension ref="A1:E5"/><sheetData>'+rows+'</sheetData></worksheet>')
print("E2E_XLSX_WRITTEN")
PY`;
const verifyWorkbook = `python3 - <<'PY'
import os
from pathlib import Path
from zipfile import ZipFile
from xml.etree import ElementTree as ET
with ZipFile(Path(os.environ["BEAR_OUTPUT_DIR"]) / "e2e-grid.xlsx") as book:
    assert book.testzip() is None
    root = ET.fromstring(book.read("xl/worksheets/sheet1.xml"))
ns = {"s": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
cells = {c.attrib["r"]: int(c.find("s:v", ns).text) for c in root.findall(".//s:c", ns)}
expected = {chr(65+c)+str(r+1): r*5+c+1 for r in range(5) for c in range(5)}
assert cells == expected, cells
print("E2E_XLSX_VERIFIED: A1:E5 = 1..25")
PY`;

const directMemoryTexts = [
	"E2E_DIRECT_MEMORY_A：我们约定暗号是北辰",
	"E2E_DIRECT_MEMORY_B：我们约定暗号是北辰",
] as const;
const port = Number(process.env.BEAR_E2E_PROVIDER_PORT ?? "3211");
// The Web E2E harness configures this test provider with the canonical model ID "rule-model".
// Keep the deterministic response script model-agnostic; model selection belongs to the tests.
let toolSequence = 0;
let completionSequence = 0;
const calls: Array<{ tool: string; args: Record<string, unknown> }> = [];
const prompts: string[] = [];
const MAX_TOOL_TRACE = 2_048;
const MAX_PROMPT_TRACE = 256;
const retriedRequests = new Set<string>();
interface ResponseHold {
	entered: boolean;
	released: boolean;
	cancelled: boolean;
	release?: () => void;
}
const responseHolds = new Map<string, ResponseHold>();
const longRichContent = `# 长回复验收

${Array.from(
	{ length: 22 },
	(_, index) =>
		`## 第 ${index + 1} 节\n\n这是用于验证长回复阅读导航与稳定滚动的第 ${index + 1} 段内容。`,
).join("\n\n")}

\`\`\`ts
const exactSource = "<safe>";
\`\`\`
`;

function text(value: unknown): string {
	if (typeof value === "string") return value;
	if (Array.isArray(value)) return value.map(text).join("\n");
	if (value && typeof value === "object") {
		const record = value as { text?: unknown; content?: unknown };
		return text(record.text ?? record.content);
	}
	return "";
}

function image(value: unknown): boolean {
	if (Array.isArray(value)) return value.some(image);
	if (!value || typeof value !== "object") return false;
	const record = value as Record<string, unknown>;
	return (
		record.type === "image" ||
		record.type === "image_url" ||
		"image_url" in record ||
		Object.values(record).some(image)
	);
}

function reply(payload: {
	model?: string;
	messages?: Array<{
		role?: string;
		content?: unknown;
		tool_calls?: Array<{ function?: { name?: string } }>;
	}>;
}) {
	const messages = payload.messages ?? [];
	const prompt = messages.map((message) => text(message.content)).join("\n");
	const hostContext =
		[...prompt.matchAll(/<host_context>\n([\s\S]*?)<\/host_context>/g)].at(-1)?.[1] ?? "";
	appendBoundedTrace(prompts, prompt, MAX_PROMPT_TRACE);
	const latestUser = [...messages].reverse().find((message) => message.role === "user");
	const latestUserContent = text(latestUser?.content);
	const current =
		[
			...latestUserContent.matchAll(/<current_user_message>\n([\s\S]*?)<\/current_user_message>/g),
		].at(-1)?.[1] ?? latestUserContent;
	const afterUser = latestUser ? messages.slice(messages.lastIndexOf(latestUser) + 1) : [];
	const currentCalls = afterUser.flatMap((message) =>
		(message.tool_calls ?? []).flatMap((call) => (call.function?.name ? [call.function.name] : [])),
	);
	const externalRun = prompt.includes("You are an independent external agent.");
	const invoke = (tool: string, args: Record<string, unknown>) => {
		appendBoundedTrace(calls, { tool, args }, MAX_TOOL_TRACE);
		return { tool, args };
	};
	const nativeHistory = current.match(/^E2E_NATIVE_HISTORY_(\d+)$/);
	if (!externalRun && nativeHistory) return { content: `E2E_NATIVE_REPLY_${nativeHistory[1]}\n` };
	const nativeDisclosure = current.match(/^E2E_NATIVE_DISCLOSURE_([a-f0-9-]+)$/);
	if (!externalRun && nativeDisclosure) {
		if (!currentCalls.includes("host_state"))
			return {
				...invoke("host_state", {
					action: "update",
					changes: [{ path: "/display/expressionId", value: "reflective" }],
				}),
				argumentsHoldId: nativeDisclosure[1],
			};
		return { content: `E2E_NATIVE_DISCLOSURE_DONE_${nativeDisclosure[1]}\n` };
	}
	if (current.includes("E2E_MODEL_ID")) {
		return { content: `E2E_MODEL_ID:${payload.model ?? "missing"}\n` };
	}
	if (!externalRun && current.includes("E2E_DELEGATE_XLSX")) {
		if (!currentCalls.includes("host_delegate"))
			return invoke("host_delegate", { instruction: "E2E_EXTERNAL_WRITE_XLSX", inputPaths: [] });
		return { content: "E2E_XLSX_DELEGATED\n" };
	}
	if (!externalRun && current.includes("E2E_DELEGATE_ARTIFACT")) {
		const hold = current.match(/E2E_DELEGATE_ARTIFACT_HOLD_([a-f0-9-]+)/);
		if (!currentCalls.includes("host_delegate"))
			return invoke("host_delegate", {
				instruction: hold
					? `E2E_EXTERNAL_WRITE_ARTIFACT_HOLD_${hold[1]}`
					: "E2E_EXTERNAL_WRITE_ARTIFACT",
				inputPaths: [],
			});
		return { content: "E2E_DELEGATED\n" };
	}
	if (!externalRun && current.includes("E2E_DELEGATE_FAILURE")) {
		if (!currentCalls.includes("host_delegate"))
			return invoke("host_delegate", {
				instruction: "E2E_EXTERNAL_PROVIDER_FAILURE",
				inputPaths: [],
			});
		return { content: "E2E_FAILURE_DELEGATED\n" };
	}
	if (!externalRun && current.includes("E2E_MEDIA_PREVIEW")) {
		if (!currentCalls.includes("host_media"))
			return invoke("host_media", { id: "continuity_light" });
		return { content: "E2E_MEDIA_READY\n" };
	}
	if (externalRun && prompt.includes("E2E_EXTERNAL_PROVIDER_FAILURE")) {
		return { errorMessage: "E2E worker provider rejected this authored failure scenario." };
	}
	if (externalRun && prompt.includes("E2E_EXTERNAL_WRITE_XLSX")) {
		const bashCalls = messages.flatMap((message) =>
			(message.tool_calls ?? []).filter((call) => call.function?.name === "bash"),
		).length;
		if (bashCalls === 0) return invoke("bash", { command: createWorkbook });
		if (bashCalls === 1) return invoke("bash", { command: verifyWorkbook });
		if (
			!messages.some(
				(message) =>
					message.role === "tool" &&
					text(message.content).includes("E2E_XLSX_VERIFIED: A1:E5 = 1..25"),
			)
		)
			return { errorMessage: "E2E worker did not verify the generated workbook." };
		return { content: "E2E_XLSX_VERIFIED: A1:E5 = 1..25\n" };
	}
	if (externalRun && prompt.includes("E2E_EXTERNAL_WRITE_ARTIFACT")) {
		const outputDirectory = /^Write deliverables beneath (.+)\.$/m.exec(prompt)?.[1];
		if (!outputDirectory) return { errorMessage: "E2E worker output directory was not supplied." };
		const outputPath = `${outputDirectory}/e2e-report.txt`;
		const workerCalls = messages.flatMap((message) =>
			(message.tool_calls ?? []).flatMap((call) =>
				call.function?.name ? [call.function.name] : [],
			),
		);
		if (!workerCalls.includes("write"))
			return invoke("write", { path: outputPath, content: artifactContent });
		if (!workerCalls.includes("read")) return invoke("read", { path: outputPath });
		if (!workerCalls.includes("bash"))
			return invoke("bash", {
				command:
					"printf 'Artifact generated by the E2E built-in Pi Worker.\\n' | cmp - \"$BEAR_OUTPUT_DIR/e2e-report.txt\" && printf 'E2E_ARTIFACT_VERIFIED\\n'",
			});
		const nativeResults = messages
			.filter((message) => message.role === "tool")
			.map((message) => text(message.content));
		if (
			!nativeResults.some((value) => value.includes(artifactContent.trim())) ||
			!nativeResults.some((value) => value.includes("E2E_ARTIFACT_VERIFIED"))
		) {
			return { errorMessage: "E2E worker did not read and verify the generated artifact." };
		}
		const hold = current.match(/E2E_EXTERNAL_WRITE_ARTIFACT_HOLD_([a-f0-9-]+)/);
		return {
			content: "EXTERNAL_ARTIFACT_DONE: native write, read and byte comparison succeeded.\n",
			...(hold ? { holdId: hold[1] } : {}),
		};
	}
	if (prompt.includes("情境切分与记忆提取专家")) {
		const marker = directMemoryTexts.find((value) => prompt.includes(value));
		const extractedMessages = [...prompt.matchAll(/^\[([^\]]+)] \[(user|assistant)] \[[^\]]+]:/gm)];
		const messageIds = extractedMessages.map((match) => match[1]);
		const assistantId = extractedMessages.findLast((match) => match[2] === "assistant")?.[1];
		return {
			content: JSON.stringify([
				{
					scene_name: "我在和用户保存明确要求记住的长期约定",
					message_ids: messageIds,
					memories: marker
						? [
								{
									content: `用户：${marker}\n角色：${marker}`,
									type: "persona",
									priority: 80,
									source_message_ids: assistantId ? [assistantId] : messageIds,
									metadata: {},
								},
							]
						: [],
				},
			]),
		};
	}
	// These markers affect only real provider requests. The browser releases the
	// response after observing Pi's native waiting/tool/retry lifecycle.
	const waiting = current.match(/E2E_WAIT_(TEXT|TOOL|RETRY)_([a-f0-9-]+)/);
	if (waiting) {
		const [, mode, holdId] = waiting;
		if (mode === "TOOL" && !currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		return {
			content: `E2E_WAIT_DONE_${holdId}\n`,
			holdId,
			...(mode === "RETRY" ? { retryId: holdId } : {}),
		};
	}
	const correction = current.match(/E2E_CORRECTION_([a-f0-9-]+)/);
	if (correction) {
		const guided = prompt.includes("<user_provided_response_guidance>");
		return {
			content: guided ? "E2E_CORRECTION_REPLACED\n" : "E2E_CORRECTION_ORIGINAL\n",
			...(guided ? { holdId: correction[1] } : {}),
		};
	}
	if (current.includes("E2E_STORY_ENTRY")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		if (!currentCalls.includes("host_choices"))
			return invoke("host_choices", {
				prompt: "要进入《未送达的回报》吗？",
				choices: [
					{ label: "进入调查", message: "进入《未送达的回报》。" },
					{ label: "以后再说", message: "《未送达的回报》以后再说。" },
				],
			});
		return { content: "E2E_STORY_ENTRY_DONE\n" };
	}
	if (current.includes("进入《未送达的回报》。")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		if (!currentCalls.includes("host_state"))
			return invoke("host_state", {
				action: "update",
				changes: [
					{ path: "/character/story/active", value: true },
					{ path: "/character/story/chapter", value: 1 },
					{ path: "/character/story/summary", value: "用户进入了未送达回报的调查。" },
					{ path: "/character/story/current_situation", value: "正在查看损坏的信号。" },
					{ path: "/character/story/unresolved", value: "信号为何损坏仍待确认。" },
				],
			});
		return { content: "E2E_STORY_STARTED_DONE\n" };
	}
	if (current.includes("先暂停《未送达的回报》。")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		if (!currentCalls.includes("host_state"))
			return invoke("host_state", {
				action: "update",
				changes: [
					{ path: "/character/story/active", value: false },
					{ path: "/character/story/current_situation", value: "调查暂停在损坏的信号处。" },
				],
			});
		return { content: "E2E_STORY_PAUSED_DONE\n" };
	}
	if (current.includes("继续《未送达的回报》。")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		if (!currentCalls.includes("host_state"))
			return invoke("host_state", {
				action: "update",
				changes: [{ path: "/character/story/active", value: true }],
			});
		return { content: "E2E_STORY_RESUMED_DONE\n" };
	}
	if (current.includes("E2E_STORY_ADVANCE")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		const chapter = Number(
			/"story":\s*\{[\s\S]*?"chapter":\s*(\d+)/u.exec(hostContext)?.[1] ?? "0",
		);
		const next = Math.min(7, chapter + 1);
		if (!currentCalls.includes("host_state"))
			return invoke("host_state", {
				action: "update",
				changes: [
					{ path: "/character/story/active", value: next < 7 },
					{ path: "/character/story/chapter", value: next },
					{ path: "/character/story/summary", value: `E2E 已推进至第 ${next} 阶段。` },
					{
						path: "/character/story/current_situation",
						value: next < 7 ? `正在处理第 ${next} 阶段。` : "调查已经结束。",
					},
					{
						path: "/character/story/unresolved",
						value: next < 7 ? `第 ${next} 阶段仍有待确认事项。` : "当前没有未解决事项。",
					},
				],
			});
		return { content: `E2E_STORY_ADVANCE_DONE_${next}\n` };
	}
	if (current.includes("E2E_STORY_CHECK_END")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		return { content: "E2E_STORY_END_CHECK_DONE\n" };
	}
	if (current.includes("E2E_MANUAL_ROLE_VISUAL")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		if (!currentCalls.includes("host_state"))
			return invoke("host_state", {
				action: "update",
				changes: [
					{ path: "/display/sceneId", value: "quiet_terminal" },
					{ path: "/display/expressionId", value: "reflective" },
				],
			});
		return { content: "E2E_MANUAL_ROLE_VISUAL_DONE\n" };
	}
	if (current.includes("E2E_MANUAL_ROLE_PRESENT")) {
		if (!currentCalls.includes("host_choices"))
			return invoke("host_choices", {
				prompt: "先看哪一张？",
				choices: [
					{ label: "极光书桌", message: "先看书桌那张图。" },
					{ label: "雪夜小路", message: "我想看看雪夜的小路。" },
				],
			});
		return { content: "E2E_MANUAL_ROLE_PRESENT_DONE\n" };
	}
	if (current.includes("先看书桌那张图。")) {
		if (!currentCalls.includes("host_state"))
			return invoke("host_state", {
				action: "update",
				changes: [
					{ path: "/display/sceneId", value: "study" },
					{ path: "/display/expressionId", value: "warm" },
				],
			});
		if (!currentCalls.includes("host_media"))
			return invoke("host_media", { id: "continuity_light" });
		return { content: "E2E_MANUAL_ROLE_RECEIVED_DONE\n" };
	}
	const memoryContextCheck = current.includes("检查记忆上下文");
	const directMemoryText = memoryContextCheck
		? undefined
		: directMemoryTexts.find((value) => current.includes(value));
	if (current.includes("E2E_TOOL_TRIGGER_DAMAGED_LOG")) {
		if (!currentCalls.includes("role_skill"))
			return invoke("role_skill", { action: "read", skillId: "undelivered-report" });
		if (currentCalls.includes("host_state"))
			return { content: "E2E_TOOL_TRIGGER_DAMAGED_LOG_DONE\n" };
		const args = {
			action: "update",
			changes: [{ path: "/character/relationship/summary", value: "用户想先看档案摘要。" }],
		};
		appendBoundedTrace(
			calls,
			{
				tool: "host_state",
				args,
			},
			MAX_TOOL_TRACE,
		);
		return { tool: "host_state", args };
	}
	if (current.includes("UX_MODEL_ERROR")) return { errorMessage: "UX model failure" };
	const content = current.includes("UX_STREAM_60_SECONDS")
		? "UX_STREAM_COMPLETE\n"
		: image(messages)
			? "VISUAL_OBSERVATION: a red square\n"
			: prompt.includes("LONG_RICH_CONTENT")
				? longRichContent
				: prompt.includes("E2E_CONTEXT_T1_EDITED") && prompt.includes("E2E_CONTEXT_T2")
					? "E2E_CONTEXT_EDITED_OK\n"
					: prompt.includes("E2E_CONTEXT_T1_ORIGINAL") && prompt.includes("E2E_CONTEXT_T2")
						? "E2E_CONTEXT_TWO_TURNS_OK\n"
						: prompt.includes("VISUAL_OBSERVATION: a red square")
							? "MAIN_USED_VISUAL_OBSERVATION\n"
							: current.includes("RICH_CONTENT_STREAM")
								? `# 交接结果

**状态：完成**

- 权威快照已读取
- 流事件已续接

| 层 | 来源 |
| --- | --- |
| 展示 | 响应式投影 |
| 内容 | Pi |

\`\`\`ts
const total = price * nights;
\`\`\`

$$
E = mc^2
$$
`
								: directMemoryText !== undefined
									? `${directMemoryText}\n`
									: memoryContextCheck
										? current.includes("南星") && hostContext.includes("南星")
											? "MEMORY_CONTEXT:我们约定暗号是南星\n"
											: current.includes("北辰") && hostContext.includes("北辰")
												? "MEMORY_CONTEXT:我们约定暗号是北辰\n"
												: "MEMORY_CONTEXT:ABSENT\n"
										: current.includes("规则：回复 EDITED_OK") ||
												prompt.includes("规则：回复 EDITED_OK")
											? "EDITED_OK\n"
											: current.includes("STREAM_FOCUS_HOLD")
												? "FOCUS_ONE FOCUS_TWO\n"
												: current.includes("STREAM_HOLD_A")
													? "HOLD_ONE HOLD_TWO\n"
													: current.includes("STREAM_CHECK")
														? "STREAM_ONE STREAM_TWO\n"
														: prompt.includes("你是谁")
															? "我是 E2E Rule Provider。\n"
															: prompt.includes("E2E_OK")
																? "E2E_OK\n"
																: "RULE_OK\n";
	return { content };
}

createServer(async (request, response) => {
	const holdRoute = request.url?.match(/^\/control\/holds\/([a-f0-9-]+)$/);
	if (holdRoute && (request.method === "GET" || request.method === "POST")) {
		const holdId = holdRoute[1];
		const hold: ResponseHold = responseHolds.get(holdId) ?? {
			entered: false,
			released: false,
			cancelled: false,
		};
		responseHolds.set(holdId, hold);
		if (request.method === "POST") {
			hold.released = true;
			hold.release?.();
		}
		response.writeHead(200, { "content-type": "application/json" }).end(
			JSON.stringify({
				entered: hold.entered,
				released: hold.released,
				cancelled: hold.cancelled,
			}),
		);
		return;
	}
	if (request.method === "GET" && request.url === "/trace/tools") {
		response.writeHead(200, { "content-type": "application/json" }).end(JSON.stringify({ calls }));
		return;
	}
	if (request.method === "GET" && request.url === "/trace/prompts") {
		response
			.writeHead(200, { "content-type": "application/json" })
			.end(JSON.stringify({ prompts }));
		return;
	}
	if (request.method === "GET" && request.url === "/health") {
		response.writeHead(204).end();
		return;
	}
	if (request.method !== "POST" || request.url !== "/v1/chat/completions") {
		response.writeHead(404).end();
		return;
	}
	const chunks: Buffer[] = [];
	for await (const chunk of request) chunks.push(Buffer.from(chunk));
	const payload = JSON.parse(Buffer.concat(chunks).toString("utf8")) as {
		stream?: boolean;
		messages?: Array<{ role?: string; content?: unknown }>;
	};
	const result = reply(payload);
	if ("errorMessage" in result) {
		response.writeHead(400, { "content-type": "application/json" }).end(
			JSON.stringify({
				error: { message: result.errorMessage, type: "invalid_request_error" },
			}),
		);
		return;
	}
	if ("retryId" in result && result.retryId && !retriedRequests.has(result.retryId)) {
		retriedRequests.add(result.retryId);
		// HTTP 400 avoids SDK-level retries; the retryable error text causes the
		// real AgentSession to emit auto_retry_start and retry the turn itself.
		response
			.writeHead(400, { "content-type": "application/json" })
			.end(
				JSON.stringify({ error: { message: "rate limit: E2E native retry", type: "rate_limit" } }),
			);
		return;
	}
	const waitForHold = async (holdId: string) => {
		const hold: ResponseHold = responseHolds.get(holdId) ?? {
			entered: false,
			released: false,
			cancelled: false,
		};
		responseHolds.set(holdId, hold);
		hold.entered = true;
		if (!hold.released) {
			// The owning test releases in finally; a real Pi cancellation closes
			// this response. Elapsed time must not complete a still-owned turn.
			await new Promise<void>((resolve) => {
				const finish = () => {
					response.off("close", cancelled);
					delete hold.release;
					resolve();
				};
				const cancelled = () => {
					hold.cancelled = true;
					finish();
				};
				hold.release = finish;
				response.once("close", cancelled);
			});
		}
	};
	if ("holdId" in result && result.holdId) {
		await waitForHold(result.holdId);
		if (response.destroyed) return;
	}
	const id = `chatcmpl-e2e-${++completionSequence}`;
	if ("tool" in result) {
		const toolCall = {
			id: `call_${++toolSequence}`,
			type: "function",
			function: { name: result.tool, arguments: JSON.stringify(result.args) },
		};
		if (payload.stream) {
			response.writeHead(200, { "content-type": "text/event-stream" });
			if ("argumentsHoldId" in result && result.argumentsHoldId) {
				const args = toolCall.function.arguments;
				const split = args.indexOf(',"value"');
				// Keep the native argument object incomplete until inspection. Pi
				// cannot execute before the remaining arguments and finish boundary.
				for (const [index, argumentsPart] of [args.slice(0, split), args.slice(split)].entries()) {
					response.write(
						`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { ...(index === 0 ? { role: "assistant" } : {}), tool_calls: [{ index: 0, ...(index === 0 ? { id: toolCall.id, type: "function" } : {}), function: { ...(index === 0 ? { name: result.tool } : {}), arguments: argumentsPart } }] }, finish_reason: null }] })}\n\n`,
					);
					if (index === 0) {
						await waitForHold(result.argumentsHoldId);
						if (response.destroyed) return;
					}
				}
			} else {
				response.write(
					`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { role: "assistant", tool_calls: [{ index: 0, ...toolCall }] }, finish_reason: null }] })}\n\n`,
				);
			}
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: {}, finish_reason: "tool_calls" }] })}\n\n`,
			);
			response.end("data: [DONE]\n\n");
			return;
		}
		response.writeHead(200, { "content-type": "application/json" });
		response.end(
			JSON.stringify({
				id,
				object: "chat.completion",
				choices: [
					{
						index: 0,
						message: { role: "assistant", content: null, tool_calls: [toolCall] },
						finish_reason: "tool_calls",
					},
				],
			}),
		);
		return;
	}
	if (payload.stream) {
		response.writeHead(200, { "content-type": "text/event-stream" });
		if (result.content === "UX_STREAM_COMPLETE\n") {
			for (let index = 0; index < 600; index += 1) {
				response.write(
					`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { ...(index === 0 ? { role: "assistant" } : {}), content: "·" }, finish_reason: null }] })}\n\n`,
				);
				await new Promise((resolve) => setTimeout(resolve, 100));
			}
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { content: " UX_STREAM_COMPLETE\n" }, finish_reason: null }] })}\n\n`,
			);
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: {}, finish_reason: "stop" }] })}\n\n`,
			);
			response.end("data: [DONE]\n\n");
			return;
		}
		if (result.content.includes("# 交接结果")) {
			const pieces = [
				"# 交接结果\n\n**状态",
				result.content.slice("# 交接结果\n\n**状态".length, result.content.indexOf("```ts") + 5),
				result.content.slice(result.content.indexOf("```ts") + 5, result.content.indexOf("$$") + 1),
				result.content.slice(result.content.indexOf("$$") + 1),
			];
			for (const [index, piece] of pieces.entries()) {
				response.write(
					`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { ...(index === 0 ? { role: "assistant" } : {}), content: piece }, finish_reason: null }] })}\n\n`,
				);
				await new Promise((resolve) => setTimeout(resolve, 120));
			}
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: {}, finish_reason: "stop" }] })}\n\n`,
			);
			response.end("data: [DONE]\n\n");
			return;
		}
		if (result.content === "HOLD_ONE HOLD_TWO\n") {
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { role: "assistant", content: "HOLD_ONE " }, finish_reason: null }] })}\n\n`,
			);
			// Keep the first Session running long enough to create and activate a
			// second real Session before this one settles, so the sidebar completion
			// marker is exercised deterministically.
			await new Promise((resolve) => setTimeout(resolve, 4_000));
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { content: "HOLD_TWO\n" }, finish_reason: null }] })}\n\n`,
			);
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: {}, finish_reason: "stop" }] })}\n\n`,
			);
			response.end("data: [DONE]\n\n");
			return;
		}
		if (result.content === "FOCUS_ONE FOCUS_TWO\n") {
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { role: "assistant", content: "FOCUS_ONE " }, finish_reason: null }] })}\n\n`,
			);
			await new Promise((resolve) => setTimeout(resolve, 8_000));
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { content: "FOCUS_TWO\n" }, finish_reason: null }] })}\n\n`,
			);
			response.write(
				`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: {}, finish_reason: "stop" }] })}\n\n`,
			);
			response.end("data: [DONE]\n\n");
			return;
		}
		response.write(
			`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: { role: "assistant", content: result.content }, finish_reason: null }] })}\n\n`,
		);
		response.write(
			`data: ${JSON.stringify({ id, object: "chat.completion.chunk", choices: [{ index: 0, delta: {}, finish_reason: "stop" }] })}\n\n`,
		);
		response.end("data: [DONE]\n\n");
		return;
	}
	response.writeHead(200, { "content-type": "application/json" });
	response.end(
		JSON.stringify({
			id,
			object: "chat.completion",
			choices: [
				{
					index: 0,
					message: { role: "assistant", content: result.content },
					finish_reason: "stop",
				},
			],
		}),
	);
}).listen(port, "127.0.0.1");
