import { execFile } from "node:child_process";
import { readFile } from "node:fs/promises";
import { promisify } from "node:util";
import { zhCN } from "@bear-harness/i18n/locales";
import type { ConversationHistoryResponse, RunListResponse } from "@bear-harness/protocol";
import { expect, type Page, test } from "playwright/test";
import {
	activeConversationId,
	ensureReadyForConversation,
	getBootstrap,
	providerHold,
	sendMessage,
} from "./helpers";

// Only model responses are authored. Runs, native tool execution, delivery and
// artifact bytes all come from the production Pi ACP worker and authenticated Host.
async function readRuns(page: Page, conversationId: string) {
	const { token } = await getBootstrap(page);
	const response = await page.request.post("/rpc/run.list", {
		headers: { "x-bear-web-dev-token": token },
		data: { conversationId },
	});
	const envelope = await response.json();
	expect(envelope).toMatchObject({ ok: true });
	return (envelope.data as RunListResponse).runs;
}

async function deliveredEntries(page: Page, conversationId: string, runId: string) {
	const { token } = await getBootstrap(page);
	const response = await page.request.post("/rpc/conversation.history", {
		headers: { "x-bear-web-dev-token": token },
		data: { conversationId, limit: 100 },
	});
	const envelope = await response.json();
	expect(envelope).toMatchObject({ ok: true });
	return (envelope.data as ConversationHistoryResponse).entries.filter(
		(entry) =>
			entry.type === "custom_message" &&
			entry.customType === "host_external_agent_result" &&
			typeof entry.details === "object" &&
			entry.details !== null &&
			"runId" in entry.details &&
			entry.details.runId === runId,
	);
}

test("a built-in Pi Run exposes native evidence and a genuinely downloadable Artifact", async ({
	page,
}) => {
	test.setTimeout(60_000);
	await ensureReadyForConversation(page);
	await sendMessage(page, "E2E_DELEGATE_ARTIFACT");
	const thread = page.getByRole("region", { name: zhCN.messages.conversation });
	await expect(thread.getByText("E2E_DELEGATED", { exact: true })).toBeVisible();

	const card = thread.getByRole("article", { name: "E2E_EXTERNAL_WRITE_ARTIFACT", exact: true });
	await expect(card).toHaveAttribute("data-run-status", "completed", { timeout: 30_000 });
	await card.getByRole("button", { name: zhCN.work.timeline.revealDetails }).click();
	const detail = page.getByRole("region", { name: zhCN.work.task.details });
	const instruction = detail
		.getByRole("group")
		.filter({ has: page.getByText(zhCN.work.task.instruction, { exact: true }) });
	await instruction.getByText(zhCN.work.task.instruction, { exact: true }).click();
	await expect(instruction.getByText("E2E_EXTERNAL_WRITE_ARTIFACT", { exact: true })).toBeVisible();
	await expect(detail).toContainText("EXTERNAL_ARTIFACT_DONE");
	const evidence = detail.getByRole("region", { name: zhCN.work.result.evidence });
	const nativeArgs = evidence
		.getByRole("group")
		.filter({ hasText: '"title": "bash"' })
		.filter({ hasText: "E2E_ARTIFACT_VERIFIED" });
	await nativeArgs.getByText("acp.tool_call", { exact: false }).click();
	const args = nativeArgs.getByText('"rawInput":', { exact: false });
	await expect(args).toBeVisible();
	const nativeCall = JSON.parse((await args.textContent())!);
	expect(nativeCall.rawInput.command).toBe(
		"printf 'Artifact generated by the E2E built-in Pi Worker.\\n' | cmp - \"$BEAR_OUTPUT_DIR/e2e-report.txt\" && printf 'E2E_ARTIFACT_VERIFIED\\n'",
	);
	const nativeCheck = evidence
		.getByRole("group")
		.filter({ hasText: '"status": "completed"' })
		.filter({ hasText: `"toolCallId": ${JSON.stringify(nativeCall.toolCallId)}` });
	await nativeCheck.getByText("acp.tool_call_update", { exact: false }).click();
	const output = nativeCheck.getByText('"rawOutput":', { exact: false });
	await expect(output).toBeVisible();
	expect(JSON.parse((await output.textContent())!)).toMatchObject({
		toolCallId: nativeCall.toolCallId,
		status: "completed",
		rawOutput: { content: [{ type: "text", text: "E2E_ARTIFACT_VERIFIED" }] },
	});
	await expect(detail.getByRole("button", { name: zhCN.work.interrupt, exact: true })).toHaveCount(
		0,
	);
	const artifact = detail.getByRole("button", {
		name: `${zhCN.work.timeline.viewArtifacts}: e2e-report.txt`,
		exact: true,
	});
	await expect(artifact).toBeVisible();
	const preview = page.getByRole("dialog", { name: "e2e-report.txt" });
	await expect(preview).toHaveCount(0);
	await artifact.click();
	await expect(preview).toBeVisible();
	await expect(
		preview.getByText("Artifact generated by the E2E built-in Pi Worker."),
	).toBeVisible();
	await expect(preview.getByRole("region", { name: zhCN.work.result.provenance })).toBeVisible();
	const conversationId = await activeConversationId(page);
	const digest = (await readRuns(page, conversationId))[0]?.artifacts[0]?.sha256;
	if (!digest) throw new Error("Completed Artifact has no digest");
	await expect(preview.getByText(digest, { exact: true })).toBeVisible();

	const downloadPromise = page.waitForEvent("download");
	await preview.getByRole("button", { name: zhCN.work.download }).click();
	const download = await downloadPromise;
	expect(download.suggestedFilename()).toBe("e2e-report.txt");
	const path = await download.path();
	if (!path) throw new Error("Artifact download has no local file");
	expect(await readFile(path, "utf8")).toBe("Artifact generated by the E2E built-in Pi Worker.\n");
});

test("media opens above a persistent two-column result workspace without selecting results automatically", async ({
	page,
}) => {
	test.setTimeout(60_000);
	await page.setViewportSize({ width: 1920, height: 1080 });
	await ensureReadyForConversation(page);
	await sendMessage(page, "E2E_MEDIA_PREVIEW");
	const card = page.getByRole("region", { name: "极昼的来处" });
	const mediaTrigger = card.getByRole("button", { name: zhCN.messages.openMedia });
	await expect(card.getByRole("img", { name: "极昼的来处" })).toBeVisible();
	await expect(page.getByRole("dialog")).toHaveCount(0);
	await sendMessage(page, "E2E_DELEGATE_ARTIFACT");
	const artifactTrigger = page.getByRole("button", {
		name: `${zhCN.work.timeline.viewArtifacts}: e2e-report.txt`,
		exact: true,
	});
	await expect(artifactTrigger).toBeVisible({ timeout: 30_000 });
	const result = page.getByRole("dialog", { name: "e2e-report.txt" });
	await expect(result).toHaveCount(0);
	await artifactTrigger.click();
	await expect(result.getByText("Artifact generated by the E2E built-in Pi Worker.")).toBeVisible();
	await expect(page.getByRole("img", { name: "极昼值守中", exact: true })).toHaveCount(0);
	const main = await page.getByRole("main").boundingBox();
	const resultBox = await result.boundingBox();
	if (!main || !resultBox) throw new Error("Result workspace has no visible geometry");
	expect(resultBox.x).toBeGreaterThanOrEqual(main.x + main.width - 1);
	expect(resultBox.width).toBeGreaterThan(600);
	const composer = page.getByRole("textbox", { name: zhCN.composer.messageInputLabel });
	await composer.fill("边看结果边继续聊");
	await expect(result).toBeVisible();
	await mediaTrigger.click();
	const viewer = page.getByRole("dialog", { name: "极昼的来处" });
	await expect(viewer).toBeVisible();
	const picture = viewer.getByRole("img", { name: "极昼的来处" });
	await expect(picture).toBeVisible();
	await expect
		.poll(() => picture.evaluate((image: HTMLImageElement) => image.naturalWidth))
		.toBeGreaterThan(0);
	await viewer.getByRole("button", { name: zhCN.messages.expandMedia }).click();
	await expect(viewer).toHaveJSProperty("clientWidth", 1920);
	await viewer.getByRole("button", { name: zhCN.messages.originalMediaSize }).click();
	await expect(viewer.getByRole("button", { name: zhCN.messages.fitMedia })).toBeVisible();
	await page.keyboard.press("Escape");
	await expect(viewer).toHaveCount(0);
	await expect(mediaTrigger).toBeFocused();
	await expect(result).toBeVisible();
	await expect(composer).toHaveValue("边看结果边继续聊");
	await result.getByRole("button", { name: zhCN.work.result.close }).click();
	await expect(page.getByRole("img", { name: "极昼值守中", exact: true })).toBeVisible();

	await page.setViewportSize({ width: 1280, height: 800 });
	await artifactTrigger.click();
	await expect(result).toBeVisible();
	await expect
		.poll(async () => {
			const drawer = await result.boundingBox();
			return drawer ? Math.round(drawer.x + drawer.width) : undefined;
		})
		.toBe(1280);
	const drawer = await result.boundingBox();
	expect(drawer?.x).toBeGreaterThan(0);
	await result.getByRole("button", { name: zhCN.work.result.close }).click();
	await page.setViewportSize({ width: 390, height: 844 });
	await mediaTrigger.click();
	await expect(viewer).toHaveJSProperty("clientWidth", 390);
	await expect(viewer).toHaveJSProperty("clientHeight", 844);
	await expect(viewer.getByRole("img", { name: "极昼的来处" })).toBeVisible();
	await viewer.getByRole("button", { name: zhCN.messages.closeMedia }).click();
	await artifactTrigger.click();
	await expect(result).toHaveJSProperty("clientWidth", 390);
	await result.getByRole("button", { name: zhCN.work.result.close }).click();

	await page.setViewportSize({ width: 1920, height: 1080 });
	const originalConversation = await activeConversationId(page);
	await artifactTrigger.click();
	await page.getByRole("button", { name: zhCN.sidebar.newConversation, exact: true }).click();
	await expect(result).toHaveCount(0);
	await page
		.getByRole("navigation", { name: zhCN.sidebar.conversations })
		.locator(`[data-conversation-id="${originalConversation}"]`)
		.click();
	await expect(artifactTrigger).toBeVisible();
	await expect(result).toHaveCount(0);
	await expect(viewer).toHaveCount(0);
});

test("a generated workbook downloads with the real A1:E5 values", async ({ page }) => {
	test.setTimeout(60_000);
	await ensureReadyForConversation(page);
	await sendMessage(page, "E2E_DELEGATE_XLSX");
	const card = page
		.getByRole("region", { name: zhCN.messages.conversation })
		.getByRole("article", { name: "E2E_EXTERNAL_WRITE_XLSX", exact: true });
	await expect
		.poll(
			async () => {
				const status = await card.getAttribute("data-run-status");
				return status && ["completed", "failed", "cancelled", "forced_termination"].includes(status)
					? status
					: undefined;
			},
			{ timeout: 30_000 },
		)
		.toBeTruthy();
	await card.getByRole("button", { name: zhCN.work.timeline.revealDetails }).click();
	const detail = page.getByRole("region", { name: zhCN.work.task.details });
	const runStatus = await card.getAttribute("data-run-status");
	if (runStatus !== "completed") {
		await expect(detail).not.toContainText("正在加载任务…");
		const acpError = detail.getByText("acp.error", { exact: false });
		if ((await acpError.count()) === 1) await acpError.click();
		for (const update of await detail.getByText("acp.tool_call_update", { exact: false }).all()) {
			await update.click();
		}
		throw new Error(`Workbook Run settled as ${runStatus}: ${await detail.innerText()}`);
	}
	await expect(detail).toContainText("E2E_XLSX_VERIFIED: A1:E5 = 1..25");
	const result = page.getByRole("dialog", { name: "e2e-grid.xlsx" });
	await expect(result).toHaveCount(0);
	await detail
		.getByRole("button", {
			name: `${zhCN.work.timeline.viewArtifacts}: e2e-grid.xlsx`,
			exact: true,
		})
		.click();
	await expect(result.getByRole("region", { name: zhCN.work.result.provenance })).toBeVisible();
	const downloading = page.waitForEvent("download");
	await result.getByRole("button", { name: zhCN.work.download }).click();
	const download = await downloading;
	expect(download.suggestedFilename()).toBe("e2e-grid.xlsx");
	const path = await download.path();
	if (!path) throw new Error("Workbook download has no local file");
	// Inspect the downloaded ZIP, not the provider's claimed summary or Host metadata.
	const { stdout } = await promisify(execFile)(
		"python3",
		[
			"-c",
			`
import json, sys
from zipfile import ZipFile
from xml.etree import ElementTree as ET
with ZipFile(sys.argv[1]) as book:
    assert book.testzip() is None
    root = ET.fromstring(book.read("xl/worksheets/sheet1.xml"))
ns = {"s": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
print(json.dumps({c.attrib["r"]: int(c.find("s:v", ns).text) for c in root.findall(".//s:c", ns)}))
`,
			path,
		],
		{ timeout: 10_000 },
	);
	const expected = Object.fromEntries(
		Array.from({ length: 25 }, (_, index) => [
			`${String.fromCharCode(65 + (index % 5))}${Math.floor(index / 5) + 1}`,
			index + 1,
		]),
	);
	expect(JSON.parse(stdout)).toEqual(expected);
});

test("a busy origin receives one durable result while another conversation remains selected", async ({
	page,
}) => {
	test.setTimeout(90_000);
	await ensureReadyForConversation(page);
	const origin = await activeConversationId(page);
	const worker = providerHold(page);
	const originTurn = providerHold(page);
	try {
		await sendMessage(page, `E2E_DELEGATE_ARTIFACT_HOLD_${worker.id}`);
		await worker.entered();
		await expect(page.getByTestId("conversation-activity")).toBeHidden();
		const [run] = await readRuns(page, origin);
		if (!run) throw new Error("Delegation produced no Run");
		await sendMessage(page, `E2E_WAIT_TEXT_${originTurn.id}`);
		await originTurn.entered();
		const [createdResponse] = await Promise.all([
			page.waitForResponse(
				(response) =>
					response.request().method() === "POST" &&
					response.url().includes("/rpc/conversation.create"),
			),
			page.getByRole("button", { name: zhCN.sidebar.newConversation, exact: true }).click(),
		]);
		const created = await createdResponse.json();
		expect(created).toMatchObject({ ok: true, data: { conversationId: expect.any(String) } });
		const other = await activeConversationId(page, created.data.conversationId);
		expect(other).not.toBe(origin);
		await worker.release();
		await expect.poll(async () => (await readRuns(page, origin))[0]?.status).toBe("completed");
		expect((await readRuns(page, origin))[0]?.resultReportedAt).toBeUndefined();
		expect(await deliveredEntries(page, origin, run.id)).toEqual([]);
		await activeConversationId(page, other);
		await expect(page.getByRole("dialog", { name: "e2e-report.txt" })).toHaveCount(0);
		await originTurn.release();
		await expect
			.poll(async () => (await deliveredEntries(page, origin, run.id)).length, { timeout: 30_000 })
			.toBe(1);
		await expect
			.poll(async () => (await readRuns(page, origin))[0]?.resultReportedAt)
			.toEqual(expect.any(String));
		expect(await deliveredEntries(page, other, run.id)).toEqual([]);
		await activeConversationId(page, other);
		await page.reload();
		await activeConversationId(page, other);
		expect(await deliveredEntries(page, origin, run.id)).toHaveLength(1);
		await page.locator(`[data-conversation-id="${origin}"]`).click();
		await expect(
			page.getByRole("button", {
				name: `${zhCN.work.timeline.viewArtifacts}: e2e-report.txt`,
				exact: true,
			}),
		).toBeVisible();
		await expect(page.getByRole("dialog", { name: "e2e-report.txt" })).toHaveCount(0);
	} finally {
		await worker.release();
		await originTurn.release();
	}
});

test("native Worker interruption exposes resume and cancellation without claiming completion", async ({
	page,
}) => {
	test.setTimeout(60_000);
	await ensureReadyForConversation(page);
	const hold = providerHold(page);
	try {
		await sendMessage(page, `E2E_DELEGATE_ARTIFACT_HOLD_${hold.id}`);
		await hold.entered();
		const card = page
			.getByRole("region", { name: zhCN.messages.conversation })
			.getByRole("article", { name: `E2E_EXTERNAL_WRITE_ARTIFACT_HOLD_${hold.id}`, exact: true });
		await card.getByRole("button", { name: zhCN.work.timeline.revealDetails }).click();
		const detail = page.getByRole("region", { name: zhCN.work.task.details });
		await detail.getByRole("button", { name: zhCN.work.interrupt, exact: true }).click();
		await hold.cancelled();
		await expect(card).toHaveAttribute("data-run-status", "interrupted");
		await expect(detail.getByRole("button", { name: zhCN.work.resume, exact: true })).toBeEnabled();
		await detail.getByRole("button", { name: zhCN.work.timeline.stopRun, exact: true }).click();
		await expect(card).toHaveAttribute("data-run-status", "cancelled");
		await expect(detail.getByRole("button", { name: zhCN.work.resume, exact: true })).toHaveCount(
			0,
		);
		await expect(page.getByRole("dialog", { name: "e2e-report.txt" })).toHaveCount(0);
	} finally {
		await hold.release();
	}
});

test("resuming a confirmed native pause completes the same Run", async ({ page }) => {
	test.setTimeout(60_000);
	await ensureReadyForConversation(page);
	const origin = await activeConversationId(page);
	const hold = providerHold(page);
	try {
		await sendMessage(page, `E2E_DELEGATE_ARTIFACT_HOLD_${hold.id}`);
		await hold.entered();
		const card = page
			.getByRole("region", { name: zhCN.messages.conversation })
			.getByRole("article", { name: `E2E_EXTERNAL_WRITE_ARTIFACT_HOLD_${hold.id}`, exact: true });
		const runId = await card.getAttribute("data-run-id");
		await card.getByRole("button", { name: zhCN.work.timeline.revealDetails }).click();
		const detail = page.getByRole("region", { name: zhCN.work.task.details });
		await detail.getByRole("button", { name: zhCN.work.interrupt, exact: true }).click();
		await hold.cancelled();
		await expect(card).toHaveAttribute("data-run-status", "interrupted");
		await hold.release();
		await detail.getByRole("button", { name: zhCN.work.resume, exact: true }).click();
		await expect(card).toHaveAttribute("data-run-status", "completed", { timeout: 30_000 });
		expect((await readRuns(page, origin)).map((run) => run.id)).toEqual([runId]);
		await expect(
			card.getByRole("button", {
				name: `${zhCN.work.timeline.viewArtifacts}: e2e-report.txt`,
				exact: true,
			}),
		).toBeVisible();
		await expect(page.getByRole("dialog", { name: "e2e-report.txt" })).toHaveCount(0);
	} finally {
		await hold.release();
	}
});

test("a real worker provider failure remains inspectable without a result-preview dead end", async ({
	page,
}) => {
	test.setTimeout(60_000);
	await ensureReadyForConversation(page);
	await sendMessage(page, "E2E_DELEGATE_FAILURE");
	const card = page
		.getByRole("region", { name: zhCN.messages.conversation })
		.getByRole("article", { name: "E2E_EXTERNAL_PROVIDER_FAILURE", exact: true });
	await expect(card).toHaveAttribute("data-run-status", "failed", { timeout: 30_000 });
	await card.getByRole("button", { name: zhCN.work.timeline.revealDetails }).click();
	const detail = page.getByRole("region", { name: zhCN.work.task.details });
	await expect(detail).toContainText(
		"E2E worker provider rejected this authored failure scenario.",
	);
	await expect(detail.getByRole("button", { name: zhCN.work.resume, exact: true })).toHaveCount(0);
	await expect(card.getByRole("list", { name: zhCN.work.result.tabsLabel })).toHaveCount(0);
	await expect(detail.getByRole("button", { name: zhCN.work.task.requestAgain })).toBeEnabled();
	await expect(page.getByRole("dialog", { name: "e2e-report.txt" })).toHaveCount(0);
});
