import { zhCN } from "@bear-harness/i18n/locales";
import { expect, test } from "playwright/test";
import { ensureReadyForConversation, sendMessage } from "./helpers";

test("an external Run completes into a verified previewable and downloadable Artifact", async ({
	page,
}) => {
	test.setTimeout(45_000);
	await ensureReadyForConversation(page);
	await sendMessage(page, "E2E_DELEGATE_ARTIFACT");
	const thread = page.getByRole("region", { name: zhCN.messages.conversation });
	await expect(thread.getByText("E2E_DELEGATED", { exact: true })).toBeVisible();

	const artifact = page.getByRole("button", { name: /查看成果: e2e-report\.txt/ });
	await expect(artifact).toBeVisible({ timeout: 30_000 });
	await artifact.click();
	const preview = page.getByRole("dialog", { name: "e2e-report.txt" });
	await expect(preview).toBeVisible();
	await expect(preview.getByText("Artifact generated by the E2E external Run.")).toBeVisible();
	await expect(preview.getByRole("region", { name: zhCN.work.result.provenance })).toBeVisible();
	await expect(preview.getByText(/^[a-f0-9]{64}$/)).toHaveCount(1);

	const downloadPromise = page.waitForEvent("download");
	await preview.getByRole("button", { name: zhCN.work.download }).click();
	const download = await downloadPromise;
	expect(download.suggestedFilename()).toBe("e2e-report.txt");
});
